// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: agent.proto

// Agent channel between SwipeShield agents (on monitored servers) and the
// manager (the swipeshield gateway). Agents dial OUT to the manager, so they
// work behind NAT with no inbound ports on monitored hosts.

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsInfo        string                 `protobuf:"bytes,3,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *EnrollResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AgentToManager struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentToManager_Heartbeat
	//	*AgentToManager_Event
	Msg           isAgentToManager_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToManager) Reset() {
	*x = AgentToManager{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToManager) ProtoMessage() {}

func (x *AgentToManager) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToManager.ProtoReflect.Descriptor instead.
func (*AgentToManager) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentToManager) GetMsg() isAgentToManager_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentToManager) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentToManager_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToManager) GetEvent() *SecurityEvent {
	if x != nil {
		if x, ok := x.Msg.(*AgentToManager_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentToManager_Msg interface {
	isAgentToManager_Msg()
}

type AgentToManager_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentToManager_Event struct {
	Event *SecurityEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*AgentToManager_Heartbeat) isAgentToManager_Msg() {}

func (*AgentToManager_Event) isAgentToManager_Msg() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsInfo        string                 `protobuf:"bytes,3,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Heartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Heartbeat) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

type SecurityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityEvent) Reset() {
	*x = SecurityEvent{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEvent) ProtoMessage() {}

func (x *SecurityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEvent.ProtoReflect.Descriptor instead.
func (*SecurityEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SecurityEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *SecurityEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SecurityEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ManagerToAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // "ping", "ack"
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerToAgent) Reset() {
	*x = ManagerToAgent{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerToAgent) ProtoMessage() {}

func (x *ManagerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerToAgent.ProtoReflect.Descriptor instead.
func (*ManagerToAgent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ManagerToAgent) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ManagerToAgent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x14swipeshield.agent.v1\"Z\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_info\x18\x03 \x01(\tR\x06osInfo\"[\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x95\x01\n" +
	"\x0eAgentToManager\x12?\n" +
	"\theartbeat\x18\x01 \x01(\v2\x1f.swipeshield.agent.v1.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\x05event\x18\x02 \x01(\v2#.swipeshield.agent.v1.SecurityEventH\x00R\x05eventB\x05\n" +
	"\x03msg\"P\n" +
	"\tHeartbeat\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_info\x18\x03 \x01(\tR\x06osInfo\"M\n" +
	"\rSecurityEvent\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"D\n" +
	"\x0eManagerToAgent\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload2\xbd\x01\n" +
	"\fAgentService\x12S\n" +
	"\x06Enroll\x12#.swipeshield.agent.v1.EnrollRequest\x1a$.swipeshield.agent.v1.EnrollResponse\x12X\n" +
	"\x06Stream\x12$.swipeshield.agent.v1.AgentToManager\x1a$.swipeshield.agent.v1.ManagerToAgent(\x010\x01B=Z;github.com/binaryguardia/swipeshield/internal/agent/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_proto_goTypes = []any{
	(*EnrollRequest)(nil),  // 0: swipeshield.agent.v1.EnrollRequest
	(*EnrollResponse)(nil), // 1: swipeshield.agent.v1.EnrollResponse
	(*AgentToManager)(nil), // 2: swipeshield.agent.v1.AgentToManager
	(*Heartbeat)(nil),      // 3: swipeshield.agent.v1.Heartbeat
	(*SecurityEvent)(nil),  // 4: swipeshield.agent.v1.SecurityEvent
	(*ManagerToAgent)(nil), // 5: swipeshield.agent.v1.ManagerToAgent
}
var file_agent_proto_depIdxs = []int32{
	3, // 0: swipeshield.agent.v1.AgentToManager.heartbeat:type_name -> swipeshield.agent.v1.Heartbeat
	4, // 1: swipeshield.agent.v1.AgentToManager.event:type_name -> swipeshield.agent.v1.SecurityEvent
	0, // 2: swipeshield.agent.v1.AgentService.Enroll:input_type -> swipeshield.agent.v1.EnrollRequest
	2, // 3: swipeshield.agent.v1.AgentService.Stream:input_type -> swipeshield.agent.v1.AgentToManager
	1, // 4: swipeshield.agent.v1.AgentService.Enroll:output_type -> swipeshield.agent.v1.EnrollResponse
	5, // 5: swipeshield.agent.v1.AgentService.Stream:output_type -> swipeshield.agent.v1.ManagerToAgent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentToManager_Heartbeat)(nil),
		(*AgentToManager_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
